---
title: "Introduction to user interface functions"
output: github_document
---

```{r, message = FALSE, tidy = FALSE, echo = F}
## knitr configuration: http://yihui.name/knitr/options#chunk_options
library(knitr)
showMessage <- FALSE
showWarning <- TRUE
set_alias(w = "fig.width", h = "fig.height", res = "results")
opts_chunk$set(comment = "##", error= TRUE, warning = showWarning, message = showMessage,
               tidy = FALSE, cache = FALSE, echo = TRUE,
               fig.width = 7, fig.height = 7, dev.args = list(family = "sans"),
               fig.path = "man/figures")
## for rgl
## knit_hooks$set(rgl = hook_rgl, webgl = hook_webgl)
## for animation
opts_knit$set(animation.fun = hook_ffmpeg_html)
## R configuration
options(width = 116, scipen = 5)
```

# Introduction to user functions

## `regemedint()`

```{r}
library(regmedint)
library(tidyverse)
## Prepare dataset
vv2015 <- read_delim(file = "../tests/reference_results/data-valeri-vanderweele-2015.txt",
                     delim = " ") %>%
    ## Following R convention, an event indicator is used.
    mutate(event = if_else(cens == 0, 1L, 0L)) %>%
    select(-cens)

regmedint_obj <- regmedint(data = vv2015,
                           ## Variables
                           yvar = "y",
                           avar = "x",
                           mvar = "m",
                           cvar = c("c"),
                           eventvar = "event",
                           ## Values at which effects are evaluated
                           a0 = 0,
                           a1 = 1,
                           m_cde = 1,
                           c_cond = 0.5,
                           ## Model types
                           mreg = "logistic",
                           yreg = "survAFT_weibull",
                           ## Additional specification
                           interaction = TRUE,
                           casecontrol = FALSE)
```

## `print()` for `regmedint
```{r}
print(regmedint)
print(regmedint, m_cde = 0, c_cond = 1)
```

## `coef()` for `regmedint`
```{r}
coef(regmedint)
coef(regmedint, m_cde = 0, c_cond = 1)
```

## `confint()` for `regmedint`

## `summary()` for `regmedint`

## `coef()` for `summary_regmedint`
